---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker.io/golang:1.18beta1-alpine  
    commands:
      - "apk add build-base"
      - "go build"
  - name: test
    image: docker.io/golang:1.18beta1-alpine  
    commands:
      - "apk add build-base"
      - "go test"
